-- Create Constraints on table DD_Freightline
ALTER TABLE DD_FreightLine ADD CONSTRAINT ddfreight_ddfreightline FOREIGN KEY (dd_freight_id) REFERENCES DD_Freight MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DD_FreightLine ADD CONSTRAINT mfreightcategory_ddfreightline FOREIGN KEY (m_freightcategory_id) REFERENCES m_freightcategory (m_freightcategory_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DD_FreightLine ADD CONSTRAINT cuom_ddfreightline FOREIGN KEY (c_uom_id) REFERENCES c_uom (c_uom_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DD_FreightLine ADD CONSTRAINT mfreight_ddfreightline FOREIGN KEY (m_freight_id) REFERENCES m_freight (m_freight_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DD_FreightLine ADD CONSTRAINT mproduct_ddfreightline FOREIGN KEY (m_product_id) REFERENCES m_product (m_product_id) MATCH SIMPLE
 ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;